### ISSUE TITLE
Permission denied on /scripts files

### ISSUE THREAD

**Issue by lorismaz** [dirkdk/docker-rails-demo#3]
Hello,

What should be the permissions on /scripts files? I always have Permission denied when building the docker image.

```
/bin/sh: 1: scripts/potential_asset_precompile.sh: Permission denied
The command '/bin/sh -c scripts/potential_asset_precompile.sh $precompileassets' returned a non-zero code: 126
```

**Comment by dirkdk** [comment]
the files checked in have pretty liberal permissions. I would suggest `chmod 755`.

As most people have no problem with this, what directory on your local host machine are you using? We normally use `/Users/<username>/projects`
