### ISSUE TITLE
Issue with asset:precompile and master key

### ISSUE THREAD

**Issue by castlese** [dirkdk/docker-rails-demo#5]
When rake assets:precompile was run, I got this issue:

`Missing encryption key to decrypt file with. Ask your team for your master key and write it to /opt/boundless/config/master.key or put it in the ENV['RAILS_MASTER_KEY']`

Did you experience this? I fixed it using the suggested method in [this comment](https://github.com/rails/rails/issues/32947#issuecomment-470380517) from an issue in the rails repo. 

Did you or anyone else encounter this? Is there a better way to address?

**Comment by dirkdk** [comment]
master.key is used for Rails 5.2 encrypted credentials. This file should never be checked in, hence is it not in this repo.

you should create your own at `config/master.key`

**Comment by castlese** [comment]
Thanks @dirkdk. That's not really answering my issue unfortunately. I understand that the master.key is not part of the version control and should be manually added. However, even when there is a master.key present I experience issues in precompiling assets on a docker build. There's more detail in the rails repo issue I linked to. 

I still didn't get to the bottom of it and for now have actually decided not to use Docker

**Comment by dirkdk** [comment]
@castlese I updated the README.md with an explanation how to create a [master.key and credentials.yml.enc](https://github.com/dirkdk/docker-rails-demo#creating-a-new-configmasterkey-and-configcredentialsymlenc)

**Comment by castlese** [comment]
@dirkdk good to have the documentation updated but as I said, that's not my issue. I know how to manage credentials and use the master.key. 

The issue is that master.key is not available during precompilation of assets in Docker build (to keep it out of source control it is in .dockerignore and .gitignore). There's lots of further info in [this issue](https://github.com/rails/rails/issues/32947#issuecomment-470380517) on the rails repo.

**Comment by eliasglyptis** [comment]
Funny how credentials are needed to compile assets.

**Comment by kaka-ruto** [comment]
Facing this issue today too, wish it got attention

**Comment by nubigram** [comment]
2024, I have the same problem for asset compilation...
